export type Listing = { id: string; title: string; price: number | null; url: string; location?: string; postedAt?: string; imageUrl?: string; body?: string };
export type StorageType = 'NVMe' | 'SSD' | 'HDD' | 'eMMC';
export type ParsedSpecs = { cpu?: string; ramGb?: number; storageGb?: number; storageType?: StorageType; gpu?: string; kind?: 'desktop' | 'laptop'; evidence: string[] };
export type Analysis = Listing & { specs: ParsedSpecs; valueScore: number | null; confidence: 'high' | 'medium' | 'low'; flags: string[]; reasons: string[]; savedAt: number };
export type AiListingAnalysis = {
  id: string;
  title: string;
  price: number | null;
  url: string;
  location?: string;
  cpu: string;
  cpuPerformanceScore: number;
  cpuPerformanceSummary: string;
  ram: string;
  storage: string;
  gpu: string;
  score: number;
  recommendation: '추천' | '보통' | '주의';
  summary: string;
  strengths: string;
  cautions: string;
};
